if(EXISTS "/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/base/tests/arccore_base.tests[1]_tests.cmake")
  include("/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/base/tests/arccore_base.tests[1]_tests.cmake")
else()
  add_test(arccore_base.tests_NOT_BUILT arccore_base.tests_NOT_BUILT)
endif()
