if(EXISTS "/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/concurrency/tests/arccore_concurrency.tests[1]_tests.cmake")
  include("/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/concurrency/tests/arccore_concurrency.tests[1]_tests.cmake")
else()
  add_test(arccore_concurrency.tests_NOT_BUILT arccore_concurrency.tests_NOT_BUILT)
endif()
