if(EXISTS "/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/src/arcane/cartesianmesh/tests/arcane_cartesianmesh.tests[1]_tests.cmake")
  include("/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/src/arcane/cartesianmesh/tests/arcane_cartesianmesh.tests[1]_tests.cmake")
else()
  add_test(arcane_cartesianmesh.tests_NOT_BUILT arcane_cartesianmesh.tests_NOT_BUILT)
endif()
