// -*- C++ -*-
#ifndef ALIEN_LOGGER_PRECOMP_H
#define ALIEN_LOGGER_PRECOMP_H
/* Author : havep at Wed Jun 27 14:26:14 2012
 * Generated by createNew
 */

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#include "alien/AlienLoggerExport.h"
#include <alien/AlienLegacyConfig.h>

#endif
