add_test([=[Array.Swap1]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.Swap1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.Swap1]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.Swap2]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.Swap2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.Swap2]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.Misc]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.Misc]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.Misc]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.Misc2]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.Misc2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.Misc2]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.SubViews]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.SubViews]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.SubViews]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.Misc3]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.Misc3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.Misc3]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.Misc4]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.Misc4]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.Misc4]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.Allocator]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.Allocator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.Allocator]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.AllocatorV2]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.AllocatorV2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.AllocatorV2]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array.DebugInfo]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array.DebugInfo]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array.DebugInfo]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SharedArray2.Misc1]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=SharedArray2.Misc1]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SharedArray2.Misc1]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SharedArray2.Misc2]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=SharedArray2.Misc2]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SharedArray2.Misc2]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SharedArray2.Misc3]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=SharedArray2.Misc3]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SharedArray2.Misc3]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Array2.Misc]=]  /work/zhaoy/Bureau/framework/build_release/lib/arccore_collections.tests [==[--gtest_filter=Array2.Misc]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Array2.Misc]=]  PROPERTIES WORKING_DIRECTORY /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  arccore_collections.tests_TESTS Array.Swap1 Array.Swap2 Array.Misc Array.Misc2 Array.SubViews Array.Misc3 Array.Misc4 Array.Allocator Array.AllocatorV2 Array.DebugInfo SharedArray2.Misc1 SharedArray2.Misc2 SharedArray2.Misc3 Array2.Misc)
