if(EXISTS "/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests/arccore_collections.tests[1]_tests.cmake")
  include("/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/collections/tests/arccore_collections.tests[1]_tests.cmake")
else()
  add_test(arccore_collections.tests_NOT_BUILT arccore_collections.tests_NOT_BUILT)
endif()
