# CMake generated Testfile for 
# Source directory: /work/zhaoy/Bureau/framework/arcane
# Build directory: /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("arccon")
subdirs("dependencies")
subdirs("axlstar")
subdirs("arccore")
subdirs("src/arcane/ios")
subdirs("src/arcane/hyoda")
subdirs("src/arcane/mono")
subdirs("src/arcane/dotnet/coreclr")
subdirs("src/arcane/parallel/mpi")
subdirs("src/arcane/parallel/thread")
subdirs("src/arcane/parallel/mpithread")
subdirs("src/arcane/utils")
subdirs("src/arcane/impl")
subdirs("src/arcane/mesh")
subdirs("src/arcane/launcher")
subdirs("src/arcane/core")
subdirs("src/arcane/geometry")
subdirs("src/arcane/corefinement")
subdirs("src/arcane/totalview")
subdirs("src/arcane/hdf5")
subdirs("src/arcane/std")
subdirs("src/arcane/aleph")
subdirs("src/arcane/driverlib")
subdirs("src/arcane/driver")
subdirs("src/arcane/accelerator/core")
subdirs("tools")
subdirs("src/arcane/tests")
subdirs("samples_build")
subdirs("src/arcane/cartesianmesh")
subdirs("../../../cea")
