# CMake generated Testfile for 
# Source directory: /work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests
# Build directory: /work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/arccore/src/message_passing_mpi/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MessagePassingMpi.Simple-mpi1 "/soft/irsrvsoft1/expl/eb/r11/el_9-x86_64/easybuild/software/impi/2021.4.0-GCC-11.2.0/mpi/2021.4.0/bin/mpiexec" "-n" "1" "/work/zhaoy/Bureau/framework/build_release/lib/arccore_message_passing_mpi.tests" "--gtest_filter=MessagePassingMpi.Simple")
set_tests_properties(MessagePassingMpi.Simple-mpi1 PROPERTIES  _BACKTRACE_TRIPLES "/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;19;add_test;/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;26;mp_add_test;/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;0;")
add_test(MessagePassingMpi.Simple-mpi2 "/soft/irsrvsoft1/expl/eb/r11/el_9-x86_64/easybuild/software/impi/2021.4.0-GCC-11.2.0/mpi/2021.4.0/bin/mpiexec" "-n" "2" "/work/zhaoy/Bureau/framework/build_release/lib/arccore_message_passing_mpi.tests" "--gtest_filter=MessagePassingMpi.Simple")
set_tests_properties(MessagePassingMpi.Simple-mpi2 PROPERTIES  _BACKTRACE_TRIPLES "/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;19;add_test;/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;27;mp_add_test;/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;0;")
add_test(MessagePassingMpi.SerializeGather-mpi3 "/soft/irsrvsoft1/expl/eb/r11/el_9-x86_64/easybuild/software/impi/2021.4.0-GCC-11.2.0/mpi/2021.4.0/bin/mpiexec" "-n" "3" "/work/zhaoy/Bureau/framework/build_release/lib/arccore_message_passing_mpi.tests" "--gtest_filter=MessagePassingMpi.SerializeGather")
set_tests_properties(MessagePassingMpi.SerializeGather-mpi3 PROPERTIES  _BACKTRACE_TRIPLES "/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;19;add_test;/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;28;mp_add_test;/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;0;")
add_test(MessagePassingMpi.Float16-mpi2 "/soft/irsrvsoft1/expl/eb/r11/el_9-x86_64/easybuild/software/impi/2021.4.0-GCC-11.2.0/mpi/2021.4.0/bin/mpiexec" "-n" "2" "/work/zhaoy/Bureau/framework/build_release/lib/arccore_message_passing_mpi.tests" "--gtest_filter=MessagePassingMpi.Float16")
set_tests_properties(MessagePassingMpi.Float16-mpi2 PROPERTIES  _BACKTRACE_TRIPLES "/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;19;add_test;/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;29;mp_add_test;/work/zhaoy/Bureau/framework/arccore/src/message_passing_mpi/tests/CMakeLists.txt;0;")
