if(EXISTS "/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/src/arcane/core/tests/arcane_core.tests[1]_tests.cmake")
  include("/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/src/arcane/core/tests/arcane_core.tests[1]_tests.cmake")
else()
  add_test(arcane_core.tests_NOT_BUILT arcane_core.tests_NOT_BUILT)
endif()
