if(EXISTS "/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/src/arcane/mesh/neo/sgraph/src/tests/SGraph.tests[1]_tests.cmake")
  include("/work/zhaoy/Bureau/framework/build_release/_common/build_all/arcane/src/arcane/mesh/neo/sgraph/src/tests/SGraph.tests[1]_tests.cmake")
else()
  add_test(SGraph.tests_NOT_BUILT SGraph.tests_NOT_BUILT)
endif()
