/*
* AlienConfig.h file, automatically generated by CMAKE.
*
*
*/

#ifndef ALIENCONFIG_H
#define ALIENCONFIG_H

#define ALIEN_VERSION "1.2.0"
#define ALIEN_VERSION_MAJOR 1
#define ALIEN_VERSION_MINOR 2
#define ALIEN_VERSION_PATCH 0

/* Defines that depends on compiler */
//Tag var as a voluntary unused variable.
//Works with any compiler but might be improved by using attribute.
#define ALIEN_UNUSED(var) do { (void)(var) ; } while(0)
#ifndef ALIEN_UNUSED_PARAM
#if ((defined(_MSVC_LANG) && _MSVC_LANG >= 201703L) || __cplusplus >= 201703L)
#  define ALIEN_UNUSED_PARAM [[maybe_unused]]
#else
#  define ALIEN_UNUSED_PARAM
#endif
#endif

// LibXml2
#define ALIEN_USE_LIBXML2

// HDF5
#define ALIEN_USE_HDF5

// Eigen3
/* #undef ALIEN_USE_EIGEN3 */

// SYCL
/* #undef ALIEN_USE_SYCL */

#endif // ALIENCONFIG_H
