// # File generated from configure. Do not edit
// # Options
#ifndef ARCANE_CORE_CONFIG_H
#define ARCANE_CORE_CONFIG_H
#define ARCANE_TYPE_INT16 ARCCORE_TYPE_INT16
#define ARCANE_TYPE_INT32 ARCCORE_TYPE_INT32
#define ARCANE_TYPE_INT64 ARCCORE_TYPE_INT64
#define ARCANE_INTEGER_MAX ARCCORE_INTEGER_MAX
#define ARCANE_INT32_MAX INT32_MAX
#define ARCANE_INT64_MAX INT64_MAX
#define ARCANE_ITEM_CONNECTIVITY_SIZE_MODE_LEGACY 1
#define ARCANE_ITEM_CONNECTIVITY_SIZE_MODE_NEW 2
#define ARCANE_ITEM_CONNECTIVITY_SIZE_MODE_DYNAMIC 3
#define ARCANE_ITEMENUMERATOR_VERSION 
#ifndef ARCANE_HAS_THREAD
#define ARCANE_HAS_THREAD
#endif
//#define ARCANE_CHECK
//#define ARCANE_DEBUG
//#define ARCANE_HAS_CUDA
//#define ARCANE_HAS_HIP
//#define ARCANE_HAS_SYCL
#ifndef ARCANE_HAS_CXX11
#define ARCANE_HAS_CXX11
#endif
#ifndef ARCANE_HAS_CXX14
#define ARCANE_HAS_CXX14
#endif
//#define ARCANE_HAS_CXX20
//#define ARCANE_HAS_ACCELERATOR_API
//#define ARCANE_HAS_ACCELERATOR
//#define ARCANE_64BIT
//#define ARCANE_REAL_LONG
//#define ARCANE_HAS_AVX
//#define ARCANE_HAS_AVX512
#ifndef ARCANE_USE_LIBXML2
#define ARCANE_USE_LIBXML2
#endif
#ifndef ARCANE_ITEM_CONNECTIVITY_SIZE_MODE
#define ARCANE_ITEM_CONNECTIVITY_SIZE_MODE 2
#endif
//#define ARCANE_USE_MPC
#ifndef ARCANE_USE_HIDDEN_VISIBILITY
#define ARCANE_USE_HIDDEN_VISIBILITY
#endif
//#define ARCANE_USE_STD_UNORDEREDMAP
#ifndef ARCANE_HAS_ARCANEMPI
#define ARCANE_HAS_ARCANEMPI
#endif
#define METIS_DEFAULT_PARTITIONER 1
#define PTSCOTCH_DEFAULT_PARTITIONER 2
#define ZOLTAN_DEFAULT_PARTITIONER 3
#define ARCANE_DEFAULT_PARTITIONER_STR "Metis"
#ifndef ARCANE_DEFAULT_PARTITIONER
#define ARCANE_DEFAULT_PARTITIONER METIS_DEFAULT_PARTITIONER
#endif
#endif // ARCANE_CORE_CONFIG_H
