#if !defined(ARCANE_PARALLEL_GHOSTITEMSVARIABLEPARALLELOPERATION_H) && !defined(ARCANE_CORE_PARALLEL_GHOSTITEMSVARIABLEPARALLELOPERATION_H)
#include "arcane/core/parallel/GhostItemsVariableParallelOperation.h"
#endif
